# Generated by Django 2.2.3 on 2019-07-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('body1', models.TextField(max_length=1000)),
                ('body2', models.TextField(max_length=1000)),
                ('body3', models.TextField(max_length=1000)),
                ('body4', models.TextField(max_length=1000)),
            ],
        ),
    ]
